### ISSUE TITLE
Removal of elements does not work in transactions

### ISSUE THREAD

**Issue by tgs266** [tgs266/KrowAlpha#23]
Using the split function does not work. @devergi do you know of a way to do this? We might have to create a new array without the item we're trying to remove. I don't know enough JS to recommend a better solution

**Comment by ghost** [comment]
I was wondering if you had meant `splice()`, but when I checked I did find employer.js used `split()`, where applicant.js correctly used `splice()`. They are quite different functions: one splits a string into an array by delimiters, while the other removes elements from an array. I must have overlooked it when I was going over your code. The next commit _should_ fix it.

**Comment by tgs266** [comment]
My bad I meant to use splice. Thanks for catching that.
